[custom]
;Proxy group
custom_proxy_group=Proxy`url-test`.*`http://cp.cloudflare.com`300,,150

;Rules - RU direct, everything else proxy
surge_ruleset=DIRECT,[]GEOSITE,RU
surge_ruleset=DIRECT,[]GEOIP,RU
surge_ruleset=DIRECT,[]GEOIP,PRIVATE
surge_ruleset=Proxy,[]MATCH

enable_rule_generator=true
overwrite_original_rules=true

