[custom]
;Proxy group
custom_proxy_group=Proxy`url-test`.*`http://cp.cloudflare.com`300,,150

;Rules - popular unblocked non-RU sites DIRECT
surge_ruleset=DIRECT,[]DOMAIN-SUFFIX,google.com
surge_ruleset=DIRECT,[]DOMAIN-SUFFIX,gstatic.com
surge_ruleset=DIRECT,[]DOMAIN-SUFFIX,googlesyndication.com
surge_ruleset=DIRECT,[]DOMAIN-SUFFIX,github.com
surge_ruleset=DIRECT,[]DOMAIN-SUFFIX,github.io
surge_ruleset=DIRECT,[]DOMAIN-SUFFIX,githubusercontent.com
surge_ruleset=DIRECT,[]DOMAIN-SUFFIX,apple.com
surge_ruleset=DIRECT,[]DOMAIN-SUFFIX,icloud.com
surge_ruleset=DIRECT,[]DOMAIN-SUFFIX,mzstatic.com
surge_ruleset=DIRECT,[]DOMAIN-SUFFIX,microsoft.com
surge_ruleset=DIRECT,[]DOMAIN-SUFFIX,live.com
surge_ruleset=DIRECT,[]DOMAIN-SUFFIX,office.com
surge_ruleset=DIRECT,[]DOMAIN-SUFFIX,amazon.com
surge_ruleset=DIRECT,[]DOMAIN-SUFFIX,wikipedia.org
surge_ruleset=DIRECT,[]DOMAIN-SUFFIX,wikimedia.org
surge_ruleset=DIRECT,[]DOMAIN-SUFFIX,stackoverflow.com
surge_ruleset=DIRECT,[]DOMAIN-SUFFIX,pinterest.com
surge_ruleset=DIRECT,[]DOMAIN-SUFFIX,championat.com
surge_ruleset=DIRECT,[]DOMAIN-SUFFIX,aliexpress.com
surge_ruleset=DIRECT,[]DOMAIN-SUFFIX,cloudflare.com
surge_ruleset=DIRECT,[]DOMAIN-SUFFIX,cloudflare-dns.com
surge_ruleset=DIRECT,[]DOMAIN-SUFFIX,habr.com
;RU by IP and domain zones
surge_ruleset=DIRECT,[]GEOIP,RU
surge_ruleset=DIRECT,[]GEOIP,PRIVATE
surge_ruleset=DIRECT,[]DOMAIN-SUFFIX,.ru
surge_ruleset=DIRECT,[]DOMAIN-SUFFIX,.рф
surge_ruleset=DIRECT,[]DOMAIN-SUFFIX,.su
;Everything else via proxy
surge_ruleset=Proxy,[]MATCH

enable_rule_generator=true
overwrite_original_rules=true
